GET http://localhost:3005/users


#####


POST http://localhost:3005/webhook
Content-Type: application/json

{
  "object": "whatsapp_business_account",
  "entry": [
    {
      "id": "293442527182997",
      "changes": [
        {
          "value": {
            "messaging_product": "whatsapp",
            "metadata": {
              "display_phone_number": "15556105902",
              "phone_number_id": "232950459911097"
            },
            "contacts": [
              {
                "profile": {
                  "name": "Lavan Adicherla"
                },
                "wa_id": "918096255759"
              }
            ],
            "messages": [
              {
                "from": "917895441429",
                "id": "203410447948670",
                "timestamp": "1713500803",
                "type": "text",
                "text": {
                  "body": "hello mam"
                }
              }
            ]
          },
          "field": "messages"
        }
      ]
    }
  ]
}


#########

POST http://localhost:3005/message
Content-Type: application/json

{
    "messaging_product": "whatsapp",
    "to": "917895441429",
    "type": "text",
    "data": {
        "text": "Hii Garu What are you doing???"
    }
}


#########

POST http://localhost:3005/message
Content-Type: application/json

{
  "messaging_product": "whatsapp",
  "recipient_type": "individual",
  "to": "917895441429",
  "type": "reaction",
  "data": {
    "message_id": "wamid.HBgMOTE3ODk1NDQxNDI5FQIAEhgSRTg0REU1Q0Q2Q0JFRjg2OUVGAA==",
    "emoji": "❤️"
  }
}


#########

POST http://localhost:3005/webhook
Content-Type: application/json

{
    "object": "whatsapp_business_account",
    "entry": [
        {
            "id": "8856996819413533",
            "changes": [
                {
                    "value": {
                        "messaging_product": "whatsapp",
                        "metadata": {
                            "display_phone_number": "16505553333",
                            "phone_number_id": "918096255759"
                        },
                        "contacts": [
                            {
                                "profile": {
                                    "name": "<CONTACT_NAME>"
                                },
                                "wa_id": "<WA_ID>"
                            }
                        ],
                        "messages": [
                            {
                                "from": "918096255759",
                                "id": "wamid.id",
                                "timestamp": "<TIMESTAMP>",
                                "type": "image",
                                "image": {
                                    "caption": "This is a caption",
                                    "mime_type": "image/jpeg",
                                    "sha256": "81d3bd8a8db4868c9520ed47186e8b7c5789e61ff79f7f834be6950b808a90d3",
                                    "id": "463004666155495"
                                }
                            }
                        ]
                    },
                    "field": "messages"
                }
            ]
        }
    ]
}